### ISSUE TITLE
Click on background to stop editing labels in model editor

### ISSUE THREAD

**Issue by michaelahokas** [ZingWorkshop/Studio#504] opened 2019-08-25 00:47 UTC
Refer to video:
[Zing - Editing labels in model editor.mp4.zip](https://github.com/ZingWorkshop/Studio/files/3537715/Zing.-.Editing.labels.in.model.editor.mp4.zip)

**Comment by aaronkennedy** [comment] 2019-09-03 15:56
Duplicate of #78

**Closed as completed** 2019-09-04 12:32 UTC
Labels: bug
